apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: czop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: czop
    app.kubernetes.io/part-of: byoc-app-qwxt
  name: czop
spec:
  rules:
  - host: czop-byoc-rqdn-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-wdcvc.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: czop
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
